name: Build wheels

on:
  workflow_call:
  # needed to trigger the workflow manually
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build_wheels:
    name: Build wheels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v7 
        with:
          python-version: "3.10"
      - name: Build wheel and install
        run: |
          python -m pip install --user --upgrade build
          python -m build
      - uses: actions/upload-artifact@v4
        with:
          name: compact-rl-wheels
          path: ./dist/*.whl


  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Build sdist
        run: pipx run build --sdist
      - uses: actions/upload-artifact@v4
        with:
          name: compact-rl-sdist
          path: dist/*.tar.gz


  test_wheels:
    name: Test wheel
    needs: [build_wheels]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v5
        with:
          pattern: compact-rl-wheels
          path: dist
          merge-multiple: true
      - name: Install from wheel and test
        # TODO run tests
        run: |
          docker run -i --rm -v ./dist:/wheel ubuntu:latest /bin/bash << 'EOF'
          set -euo pipefail
          set -x

          cd /wheel

          # Install Python & pip
          apt-get update
          apt install software-properties-common -y
          add-apt-repository ppa:deadsnakes/ppa -y
          apt-get update
          apt-get install python3.10 python3.10-venv python3.10-dev -y

          # Look for a matching wheel in the current directory
          WHEEL=$(ls compact_rl-*.whl 2>/dev/null | head -n1 || true)
          echo "Found wheel: $WHEEL"
          if [ -z "$WHEEL" ]; then
            echo "Error: No compact_rl wheel found." >&2
            exit 1
          fi

          echo "Installing $WHEEL..."
          python3.10 -m venv venv
          source venv/bin/activate
          python3 -m pip install "$WHEEL"

          # Run a basic import test (replace with pytest if needed)
          python3 -c "import compact_rl; print('Import successful')"
          EOF
